/*
 * RS-232 Serial Tool — Example main.cpp
 * Demonstrates using toolbox_wifi.h + toolbox_web.h shared headers
 *
 * This is a simplified skeleton. Copy and expand for your actual tool.
 */

#include <Arduino.h>
#include <ArduinoJson.h>
#include "toolbox_common.h"
#include "toolbox_wifi.h"
#include "toolbox_web.h"
#include "toolbox_ota.h"
#include "web_ui_gz.h"  // Generated by build_web.py

// ============ CONFIGURATION ============
#define SERIAL_TX_PIN   4   
#define SERIAL_RX_PIN   5
#define DEFAULT_BAUD    9600
#define PREFS_NS        "serial"

// ============ STATE ============
HardwareSerial SerialRS232(1);
uint32_t currentBaud = DEFAULT_BAUD;
unsigned long bytesRx = 0;
unsigned long bytesTx = 0;

// ============ WEBSOCKET HANDLER ============
void handleToolWS(AsyncWebSocketClient* client, JsonDocument& doc) {
    const char* cmd = doc["cmd"];

    if (strcmp(cmd, "status") == 0) {
        JsonDocument resp;
        resp["type"]    = "status";
        resp["rxBytes"] = bytesRx;
        resp["txBytes"] = bytesTx;
        resp["uptime"]  = millis() / 1000;
        resp["heap"]    = ESP.getFreeHeap();
        resp["baud"]    = currentBaud;
        tbWifiStatusJson(resp);   // adds mac, wifiMode, staConnected, etc.
        tbWsReply(client, resp);
    }
    else if (strcmp(cmd, "settings") == 0) {
        JsonDocument resp;
        resp["type"] = "settings";
        resp["baud"] = currentBaud;
        tbWifiSettingsJson(resp);  // adds ssid, wifiMode, staSSID, etc.
        tbWsReply(client, resp);
    }
    else if (strcmp(cmd, "sendAscii") == 0) {
        const char* data = doc["data"];
        if (data) {
            size_t len = strlen(data);
            SerialRS232.write((const uint8_t*)data, len);
            bytesTx += len;
            tbLedFlash();

            JsonDocument resp;
            resp["type"]  = "sent";
            resp["len"]   = len;
            resp["total"] = bytesTx;
            tbWsBroadcast(resp);
        }
    }
    else if (strcmp(cmd, "savewifi") == 0) {
        const char* ssid = doc["ssid"];
        const char* pass = doc["pass"];
        if (ssid && strlen(ssid) > 0 && strlen(ssid) <= 32) {
            int wifiMode = doc["wifiMode"] | -1;
            const char* staSSID = doc["staSSID"] | (const char*)NULL;
            const char* staPass = doc["staPass"] | (const char*)NULL;
            const char* mdnsHost = doc["mdnsHost"] | (const char*)NULL;
            tbWifiSave(PREFS_NS, ssid, pass ? pass : "",
                       wifiMode, staSSID, staPass, mdnsHost);
            // ^^ saves and restarts
        }
    }
    else if (strcmp(cmd, "wifiscan") == 0) {
        JsonDocument resp;
        tbWifiScanJson(resp);
        tbWsReply(client, resp);
    }
    else if (strcmp(cmd, "clearHistory") == 0) {
        bytesRx = 0;
        bytesTx = 0;
        JsonDocument resp;
        resp["type"] = "cleared";
        tbWsBroadcast(resp);
    }
}

// ============ SETUP ============
void setup() {
    Serial.begin(115200);
    delay(1000);

    tbLedBegin();
    tbWifiBegin("SerialTool", "serial1234", PREFS_NS, "serialtool");
    tbWebBegin(INDEX_HTML_GZ, INDEX_HTML_GZ_LEN, handleToolWS);
    tbOtaBegin();

    SerialRS232.begin(currentBaud, SERIAL_8N1, SERIAL_RX_PIN, SERIAL_TX_PIN);

    Serial.println("\n  RS-232 Serial Tool ready.");
    Serial.println("  Waiting for serial data...\n");
}

// ============ LOOP ============
void loop() {
    // Read RS-232 data and forward to WebSocket
    if (SerialRS232.available()) {
        uint8_t buf[256];
        int n = 0;
        while (SerialRS232.available() && n < (int)sizeof(buf)) {
            buf[n++] = SerialRS232.read();
        }
        bytesRx += n;
        tbLedFlash();

        JsonDocument doc;
        doc["type"]  = "rx";
        doc["len"]   = n;
        doc["total"] = bytesRx;
        // Convert to hex string
        String hex;
        for (int i = 0; i < n && i < 32; i++) {
            if (i > 0) hex += ' ';
            char h[3];
            snprintf(h, sizeof(h), "%02X", buf[i]);
            hex += h;
        }
        doc["hex"] = hex;
        // Convert to ASCII
        String ascii;
        for (int i = 0; i < n && i < 32; i++) {
            if (buf[i] >= 32 && buf[i] < 127) ascii += (char)buf[i];
            else if (buf[i] == '\r') ascii += "\\r";
            else if (buf[i] == '\n') ascii += "\\n";
            else ascii += '.';
        }
        doc["ascii"] = ascii;
        doc["ts"] = millis();
        tbWsBroadcast(doc);
    }

    tbWifiLoop();
    tbWebLoop();
    tbOtaLoop();
    tbLedBlink();
    yield();
}
